/**
 * Kodo Kojo - Software factory done right
 * Copyright © 2016 Kodo Kojo (infos@kodokojo.io)
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program. If not, see <http://www.gnu.org/licenses/>.
 */

export const ACCOUNT_NEW_REQUEST = 'ACCOUNT_NEW_REQUEST'
export const ACCOUNT_NEW_SUCCESS = 'ACCOUNT_NEW_SUCCESS'
export const ACCOUNT_NEW_FAILURE = 'ACCOUNT_NEW_FAILURE'
export const API_VERSION_REQUEST = 'API_VERSION_REQUEST'
export const API_VERSION_SUCCESS = 'API_VERSION_SUCCESS'
export const API_VERSION_FAILURE = 'API_VERSION_FAILURE'
export const AUTH_REQUEST = 'AUTH_REQUEST'
export const AUTH_SUCCESS = 'AUTH_SUCCESS'
export const AUTH_FAILURE = 'AUTH_FAILURE'
export const AUTH_RESET = 'AUTH_RESET'
export const CAPTCHA_INIT = 'CAPTCHA_INIT'
export const CAPTCHA_UPDATE = 'CAPTCHA_UPDATE'
export const CAPTCHA_RESET = 'CAPTCHA_RESET'
export const BRICK_REQUEST = 'BRICK_REQUEST'
export const BRICK_SUCCESS = 'BRICK_SUCCESS'
export const BRICK_FAILURE = 'BRICK_FAILURE'
export const MENU_INIT = 'MENU_INIT'
export const MENU_UPDATE = 'MENU_UPDATE'
export const PROJECT_CONFIG_REQUEST = 'PROJECT_CONFIG_REQUEST'
export const PROJECT_CONFIG_SUCCESS = 'PROJECT_CONFIG_SUCCESS'
export const PROJECT_CONFIG_FAILURE = 'PROJECT_CONFIG_FAILURE'
export const PROJECT_CONFIG_NEW_REQUEST = 'PROJECT_CONFIG_NEW_REQUEST'
export const PROJECT_CONFIG_NEW_SUCCESS = 'PROJECT_CONFIG_NEW_SUCCESS'
export const PROJECT_CONFIG_NEW_FAILURE = 'PROJECT_CONFIG_NEW_FAILURE'
export const PROJECT_CONFIG_ADD_USER_SUCCESS = 'PROJECT_CONFIG_ADD_USER_SUCCESS'
export const PROJECT_CONFIG_ADD_USER_REQUEST = 'PROJECT_CONFIG_ADD_USER_REQUEST'
export const PROJECT_CONFIG_ADD_USER_FAILURE = 'PROJECT_CONFIG_ADD_USER_FAILURE'
export const PROJECT_CONFIG_DELETE_USERS_REQUEST = 'PROJECT_CONFIG_DELETE_USERS_REQUEST'
export const PROJECT_CONFIG_DELETE_USERS_SUCCESS = 'PROJECT_CONFIG_DELETE_USERS_SUCCESS'
export const PROJECT_CONFIG_DELETE_USERS_FAILURE = 'PROJECT_CONFIG_DELETE_USERS_FAILURE'
export const PROJECT_REQUEST = 'PROJECT_REQUEST'
export const PROJECT_SUCCESS = 'PROJECT_SUCCESS'
export const PROJECT_FAILURE = 'PROJECT_FAILURE'
export const PROJECT_NEW_REQUEST = 'PROJECT_NEW_REQUEST'
export const PROJECT_NEW_SUCCESS = 'PROJECT_NEW_SUCCESS'
export const PROJECT_NEW_FAILURE = 'PROJECT_NEW_FAILURE'
export const PROJECT_UPDATE = 'PROJECT_UPDATE'
export const PREF_THEME_SET = 'PREF_THEME_SET'
export const PREF_LOCALE_SET = 'PREF_LOCALE_SET'
export const PREF_NAV_VISIBILITY_SET = 'PREF_NAV_VISIBILITY_SET'
export const USER_NEW_ID_REQUEST = 'USER_NEW_ID_REQUEST'
export const USER_NEW_ID_SUCCESS = 'USER_NEW_ID_SUCCESS'
export const USER_NEW_ID_FAILURE = 'USER_NEW_ID_FAILURE'
export const USER_NEW_REQUEST = 'USER_NEW_REQUEST'
export const USER_NEW_SUCCESS = 'USER_NEW_SUCCESS'
export const USER_NEW_FAILURE = 'USER_NEW_FAILURE'
export const USER_UPDATE_REQUEST = 'USER_UPDATE_REQUEST'
export const USER_UPDATE_SUCCESS = 'USER_UPDATE_SUCCESS'
export const USER_UPDATE_FAILURE = 'USER_UPDATE_FAILURE'
export const USER_REQUEST = 'USER_REQUEST'
export const USER_SUCCESS = 'USER_SUCCESS'
export const USER_FAILURE = 'USER_FAILURE'
export const WEBSOCKET_REQUEST = 'WEBSOCKET_REQUEST'
export const WEBSOCKET_SUCCESS = 'WEBSOCKET_SUCCESS'
export const WEBSOCKET_FAILURE = 'WEBSOCKET_FAILURE'
export const WEBSOCKET_STOP = 'WEBSOCKET_STOP'
